[Sun Jul 01, 03:57:40] $ brew doctor | tee ~/Documents/brew_doctor_`date "+%Y%m%d_%H%M%S"`.log
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libboost_atomic.dylib
  /usr/local/lib/libboost_chrono.dylib
  /usr/local/lib/libboost_container.dylib
  /usr/local/lib/libboost_context.dylib
  /usr/local/lib/libboost_coroutine.dylib
  /usr/local/lib/libboost_date_time.dylib
  /usr/local/lib/libboost_filesystem.dylib
  /usr/local/lib/libboost_graph.dylib
  /usr/local/lib/libboost_iostreams.dylib
  /usr/local/lib/libboost_locale.dylib
  /usr/local/lib/libboost_log.dylib
  /usr/local/lib/libboost_log_setup.dylib
  /usr/local/lib/libboost_math_c99.dylib
  /usr/local/lib/libboost_math_c99f.dylib
  /usr/local/lib/libboost_math_c99l.dylib
  /usr/local/lib/libboost_math_tr1.dylib
  /usr/local/lib/libboost_math_tr1f.dylib
  /usr/local/lib/libboost_math_tr1l.dylib
  /usr/local/lib/libboost_numpy.dylib
  /usr/local/lib/libboost_prg_exec_monitor.dylib
  /usr/local/lib/libboost_program_options.dylib
  /usr/local/lib/libboost_python.dylib
  /usr/local/lib/libboost_random.dylib
  /usr/local/lib/libboost_regex.dylib
  /usr/local/lib/libboost_serialization.dylib
  /usr/local/lib/libboost_signals.dylib
  /usr/local/lib/libboost_stacktrace_addr2line.dylib
  /usr/local/lib/libboost_stacktrace_basic.dylib
  /usr/local/lib/libboost_stacktrace_noop.dylib
  /usr/local/lib/libboost_system.dylib
  /usr/local/lib/libboost_thread.dylib
  /usr/local/lib/libboost_timer.dylib
  /usr/local/lib/libboost_type_erasure.dylib
  /usr/local/lib/libboost_unit_test_framework.dylib
  /usr/local/lib/libboost_wave.dylib
  /usr/local/lib/libboost_wserialization.dylib
  /usr/local/lib/libgmp.10.dylib
  /usr/local/lib/libgmpxx.4.dylib
  /usr/local/lib/libopencv_aruco.3.1.0.dylib
  /usr/local/lib/libopencv_bgsegm.3.1.0.dylib
  /usr/local/lib/libopencv_bioinspired.3.1.0.dylib
  /usr/local/lib/libopencv_calib3d.3.1.0.dylib
  /usr/local/lib/libopencv_ccalib.3.1.0.dylib
  /usr/local/lib/libopencv_core.3.1.0.dylib
  /usr/local/lib/libopencv_datasets.3.1.0.dylib
  /usr/local/lib/libopencv_dnn.3.1.0.dylib
  /usr/local/lib/libopencv_dpm.3.1.0.dylib
  /usr/local/lib/libopencv_face.3.1.0.dylib
  /usr/local/lib/libopencv_features2d.3.1.0.dylib
  /usr/local/lib/libopencv_flann.3.1.0.dylib
  /usr/local/lib/libopencv_fuzzy.3.1.0.dylib
  /usr/local/lib/libopencv_hdf.3.1.0.dylib
  /usr/local/lib/libopencv_highgui.3.1.0.dylib
  /usr/local/lib/libopencv_imgcodecs.3.1.0.dylib
  /usr/local/lib/libopencv_imgproc.3.1.0.dylib
  /usr/local/lib/libopencv_line_descriptor.3.1.0.dylib
  /usr/local/lib/libopencv_ml.3.1.0.dylib
  /usr/local/lib/libopencv_objdetect.3.1.0.dylib
  /usr/local/lib/libopencv_optflow.3.1.0.dylib
  /usr/local/lib/libopencv_photo.3.1.0.dylib
  /usr/local/lib/libopencv_plot.3.1.0.dylib
  /usr/local/lib/libopencv_reg.3.1.0.dylib
  /usr/local/lib/libopencv_rgbd.3.1.0.dylib
  /usr/local/lib/libopencv_saliency.3.1.0.dylib
  /usr/local/lib/libopencv_shape.3.1.0.dylib
  /usr/local/lib/libopencv_stereo.3.1.0.dylib
  /usr/local/lib/libopencv_stitching.3.1.0.dylib
  /usr/local/lib/libopencv_structured_light.3.1.0.dylib
  /usr/local/lib/libopencv_superres.3.1.0.dylib
  /usr/local/lib/libopencv_surface_matching.3.1.0.dylib
  /usr/local/lib/libopencv_text.3.1.0.dylib
  /usr/local/lib/libopencv_tracking.3.1.0.dylib
  /usr/local/lib/libopencv_video.3.1.0.dylib
  /usr/local/lib/libopencv_videoio.3.1.0.dylib
  /usr/local/lib/libopencv_videostab.3.1.0.dylib
  /usr/local/lib/libopencv_viz.3.1.0.dylib
  /usr/local/lib/libopencv_xfeatures2d.3.1.0.dylib
  /usr/local/lib/libopencv_ximgproc.3.1.0.dylib
  /usr/local/lib/libopencv_xobjdetect.3.1.0.dylib
  /usr/local/lib/libopencv_xphoto.3.1.0.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/aes.h
  /usr/local/include/asn1.h
  /usr/local/include/asn1_mac.h
  /usr/local/include/asn1t.h
  /usr/local/include/bio.h
  /usr/local/include/blowfish.h
  /usr/local/include/bn.h
  /usr/local/include/boost/container/detail/alloc_lib.h
  /usr/local/include/boost/predef.h
  /usr/local/include/boost/predef/architecture.h
  /usr/local/include/boost/predef/architecture/alpha.h
  /usr/local/include/boost/predef/architecture/arm.h
  /usr/local/include/boost/predef/architecture/blackfin.h
  /usr/local/include/boost/predef/architecture/convex.h
  /usr/local/include/boost/predef/architecture/ia64.h
  /usr/local/include/boost/predef/architecture/m68k.h
  /usr/local/include/boost/predef/architecture/mips.h
  /usr/local/include/boost/predef/architecture/parisc.h
  /usr/local/include/boost/predef/architecture/ppc.h
  /usr/local/include/boost/predef/architecture/pyramid.h
  /usr/local/include/boost/predef/architecture/rs6k.h
  /usr/local/include/boost/predef/architecture/sparc.h
  /usr/local/include/boost/predef/architecture/superh.h
  /usr/local/include/boost/predef/architecture/sys370.h
  /usr/local/include/boost/predef/architecture/sys390.h
  /usr/local/include/boost/predef/architecture/x86.h
  /usr/local/include/boost/predef/architecture/x86/32.h
  /usr/local/include/boost/predef/architecture/x86/64.h
  /usr/local/include/boost/predef/architecture/z.h
  /usr/local/include/boost/predef/compiler.h
  /usr/local/include/boost/predef/compiler/borland.h
  /usr/local/include/boost/predef/compiler/clang.h
  /usr/local/include/boost/predef/compiler/comeau.h
  /usr/local/include/boost/predef/compiler/compaq.h
  /usr/local/include/boost/predef/compiler/diab.h
  /usr/local/include/boost/predef/compiler/digitalmars.h
  /usr/local/include/boost/predef/compiler/dignus.h
  /usr/local/include/boost/predef/compiler/edg.h
  /usr/local/include/boost/predef/compiler/ekopath.h
  /usr/local/include/boost/predef/compiler/gcc.h
  /usr/local/include/boost/predef/compiler/gcc_xml.h
  /usr/local/include/boost/predef/compiler/greenhills.h
  /usr/local/include/boost/predef/compiler/hp_acc.h
  /usr/local/include/boost/predef/compiler/iar.h
  /usr/local/include/boost/predef/compiler/ibm.h
  /usr/local/include/boost/predef/compiler/intel.h
  /usr/local/include/boost/predef/compiler/kai.h
  /usr/local/include/boost/predef/compiler/llvm.h
  /usr/local/include/boost/predef/compiler/metaware.h
  /usr/local/include/boost/predef/compiler/metrowerks.h
  /usr/local/include/boost/predef/compiler/microtec.h
  /usr/local/include/boost/predef/compiler/mpw.h
  /usr/local/include/boost/predef/compiler/palm.h
  /usr/local/include/boost/predef/compiler/pgi.h
  /usr/local/include/boost/predef/compiler/sgi_mipspro.h
  /usr/local/include/boost/predef/compiler/sunpro.h
  /usr/local/include/boost/predef/compiler/tendra.h
  /usr/local/include/boost/predef/compiler/visualc.h
  /usr/local/include/boost/predef/compiler/watcom.h
  /usr/local/include/boost/predef/detail/_cassert.h
  /usr/local/include/boost/predef/detail/_exception.h
  /usr/local/include/boost/predef/detail/comp_detected.h
  /usr/local/include/boost/predef/detail/endian_compat.h
  /usr/local/include/boost/predef/detail/os_detected.h
  /usr/local/include/boost/predef/detail/platform_detected.h
  /usr/local/include/boost/predef/detail/test.h
  /usr/local/include/boost/predef/detail/test_def.h
  /usr/local/include/boost/predef/hardware.h
  /usr/local/include/boost/predef/hardware/simd.h
  /usr/local/include/boost/predef/hardware/simd/arm.h
  /usr/local/include/boost/predef/hardware/simd/arm/versions.h
  /usr/local/include/boost/predef/hardware/simd/ppc.h
  /usr/local/include/boost/predef/hardware/simd/ppc/versions.h
  /usr/local/include/boost/predef/hardware/simd/x86.h
  /usr/local/include/boost/predef/hardware/simd/x86/versions.h
  /usr/local/include/boost/predef/hardware/simd/x86_amd.h
  /usr/local/include/boost/predef/hardware/simd/x86_amd/versions.h
  /usr/local/include/boost/predef/language.h
  /usr/local/include/boost/predef/language/objc.h
  /usr/local/include/boost/predef/language/stdc.h
  /usr/local/include/boost/predef/language/stdcpp.h
  /usr/local/include/boost/predef/library.h
  /usr/local/include/boost/predef/library/c.h
  /usr/local/include/boost/predef/library/c/_prefix.h
  /usr/local/include/boost/predef/library/c/gnu.h
  /usr/local/include/boost/predef/library/c/uc.h
  /usr/local/include/boost/predef/library/c/vms.h
  /usr/local/include/boost/predef/library/c/zos.h
  /usr/local/include/boost/predef/library/std.h
  /usr/local/include/boost/predef/library/std/_prefix.h
  /usr/local/include/boost/predef/library/std/cxx.h
  /usr/local/include/boost/predef/library/std/dinkumware.h
  /usr/local/include/boost/predef/library/std/libcomo.h
  /usr/local/include/boost/predef/library/std/modena.h
  /usr/local/include/boost/predef/library/std/msl.h
  /usr/local/include/boost/predef/library/std/roguewave.h
  /usr/local/include/boost/predef/library/std/sgi.h
  /usr/local/include/boost/predef/library/std/stdcpp3.h
  /usr/local/include/boost/predef/library/std/stlport.h
  /usr/local/include/boost/predef/library/std/vacpp.h
  /usr/local/include/boost/predef/make.h
  /usr/local/include/boost/predef/os.h
  /usr/local/include/boost/predef/os/aix.h
  /usr/local/include/boost/predef/os/amigaos.h
  /usr/local/include/boost/predef/os/android.h
  /usr/local/include/boost/predef/os/beos.h
  /usr/local/include/boost/predef/os/bsd.h
  /usr/local/include/boost/predef/os/bsd/bsdi.h
  /usr/local/include/boost/predef/os/bsd/dragonfly.h
  /usr/local/include/boost/predef/os/bsd/free.h
  /usr/local/include/boost/predef/os/bsd/net.h
  /usr/local/include/boost/predef/os/bsd/open.h
  /usr/local/include/boost/predef/os/cygwin.h
  /usr/local/include/boost/predef/os/haiku.h
  /usr/local/include/boost/predef/os/hpux.h
  /usr/local/include/boost/predef/os/ios.h
  /usr/local/include/boost/predef/os/irix.h
  /usr/local/include/boost/predef/os/linux.h
  /usr/local/include/boost/predef/os/macos.h
  /usr/local/include/boost/predef/os/os400.h
  /usr/local/include/boost/predef/os/qnxnto.h
  /usr/local/include/boost/predef/os/solaris.h
  /usr/local/include/boost/predef/os/unix.h
  /usr/local/include/boost/predef/os/vms.h
  /usr/local/include/boost/predef/os/windows.h
  /usr/local/include/boost/predef/other.h
  /usr/local/include/boost/predef/other/endian.h
  /usr/local/include/boost/predef/other/workaround.h
  /usr/local/include/boost/predef/platform.h
  /usr/local/include/boost/predef/platform/ios.h
  /usr/local/include/boost/predef/platform/mingw.h
  /usr/local/include/boost/predef/platform/windows_desktop.h
  /usr/local/include/boost/predef/platform/windows_phone.h
  /usr/local/include/boost/predef/platform/windows_runtime.h
  /usr/local/include/boost/predef/platform/windows_store.h
  /usr/local/include/boost/predef/version.h
  /usr/local/include/boost/predef/version_number.h
  /usr/local/include/boost/python/detail/python22_fixed.h
  /usr/local/include/boost/regex.h
  /usr/local/include/boost/stacktrace/detail/pop_options.h
  /usr/local/include/boost/stacktrace/detail/push_options.h
  /usr/local/include/buffer.h
  /usr/local/include/camellia.h
  /usr/local/include/cast.h
  /usr/local/include/cmac.h
  /usr/local/include/cms.h
  /usr/local/include/conf.h
  /usr/local/include/conf_api.h
  /usr/local/include/crypto.h
  /usr/local/include/des.h
  /usr/local/include/des_old.h
  /usr/local/include/dh.h
  /usr/local/include/dsa.h
  /usr/local/include/dso.h
  /usr/local/include/dtls1.h
  /usr/local/include/e_os2.h
  /usr/local/include/ebcdic.h
  /usr/local/include/ec.h
  /usr/local/include/ecdh.h
  /usr/local/include/ecdsa.h
  /usr/local/include/engine.h
  /usr/local/include/err.h
  /usr/local/include/evp.h
  /usr/local/include/gmp.h
  /usr/local/include/gmpxx.h
  /usr/local/include/hmac.h
  /usr/local/include/idea.h
  /usr/local/include/krb5_asn.h
  /usr/local/include/kssl.h
  /usr/local/include/lhash.h
  /usr/local/include/md4.h
  /usr/local/include/md5.h
  /usr/local/include/mdc2.h
  /usr/local/include/modes.h
  /usr/local/include/obj_mac.h
  /usr/local/include/objects.h
  /usr/local/include/ocsp.h
  /usr/local/include/openssl/aes.h
  /usr/local/include/openssl/asn1.h
  /usr/local/include/openssl/asn1_mac.h
  /usr/local/include/openssl/asn1t.h
  /usr/local/include/openssl/bio.h
  /usr/local/include/openssl/blowfish.h
  /usr/local/include/openssl/bn.h
  /usr/local/include/openssl/buffer.h
  /usr/local/include/openssl/camellia.h
  /usr/local/include/openssl/cast.h
  /usr/local/include/openssl/cmac.h
  /usr/local/include/openssl/cms.h
  /usr/local/include/openssl/conf.h
  /usr/local/include/openssl/conf_api.h
  /usr/local/include/openssl/crypto.h
  /usr/local/include/openssl/des.h
  /usr/local/include/openssl/des_old.h
  /usr/local/include/openssl/dh.h
  /usr/local/include/openssl/dsa.h
  /usr/local/include/openssl/dso.h
  /usr/local/include/openssl/dtls1.h
  /usr/local/include/openssl/e_os2.h
  /usr/local/include/openssl/ebcdic.h
  /usr/local/include/openssl/ec.h
  /usr/local/include/openssl/ecdh.h
  /usr/local/include/openssl/ecdsa.h
  /usr/local/include/openssl/engine.h
  /usr/local/include/openssl/err.h
  /usr/local/include/openssl/evp.h
  /usr/local/include/openssl/hmac.h
  /usr/local/include/openssl/idea.h
  /usr/local/include/openssl/krb5_asn.h
  /usr/local/include/openssl/kssl.h
  /usr/local/include/openssl/lhash.h
  /usr/local/include/openssl/md4.h
  /usr/local/include/openssl/md5.h
  /usr/local/include/openssl/mdc2.h
  /usr/local/include/openssl/modes.h
  /usr/local/include/openssl/obj_mac.h
  /usr/local/include/openssl/objects.h
  /usr/local/include/openssl/ocsp.h
  /usr/local/include/openssl/opensslconf.h
  /usr/local/include/openssl/opensslv.h
  /usr/local/include/openssl/ossl_typ.h
  /usr/local/include/openssl/pem.h
  /usr/local/include/openssl/pem2.h
  /usr/local/include/openssl/pkcs12.h
  /usr/local/include/openssl/pkcs7.h
  /usr/local/include/openssl/pqueue.h
  /usr/local/include/openssl/rand.h
  /usr/local/include/openssl/rc2.h
  /usr/local/include/openssl/rc4.h
  /usr/local/include/openssl/ripemd.h
  /usr/local/include/openssl/rsa.h
  /usr/local/include/openssl/safestack.h
  /usr/local/include/openssl/seed.h
  /usr/local/include/openssl/sha.h
  /usr/local/include/openssl/srp.h
  /usr/local/include/openssl/srtp.h
  /usr/local/include/openssl/ssl.h
  /usr/local/include/openssl/ssl2.h
  /usr/local/include/openssl/ssl23.h
  /usr/local/include/openssl/ssl3.h
  /usr/local/include/openssl/stack.h
  /usr/local/include/openssl/symhacks.h
  /usr/local/include/openssl/tls1.h
  /usr/local/include/openssl/ts.h
  /usr/local/include/openssl/txt_db.h
  /usr/local/include/openssl/ui.h
  /usr/local/include/openssl/ui_compat.h
  /usr/local/include/openssl/whrlpool.h
  /usr/local/include/openssl/x509.h
  /usr/local/include/openssl/x509_vfy.h
  /usr/local/include/openssl/x509v3.h
  /usr/local/include/opensslconf.h
  /usr/local/include/opensslv.h
  /usr/local/include/ossl_typ.h
  /usr/local/include/pem.h
  /usr/local/include/pem2.h
  /usr/local/include/pkcs12.h
  /usr/local/include/pkcs7.h
  /usr/local/include/pqueue.h
  /usr/local/include/rand.h
  /usr/local/include/rc2.h
  /usr/local/include/rc4.h
  /usr/local/include/ripemd.h
  /usr/local/include/rsa.h
  /usr/local/include/safestack.h
  /usr/local/include/seed.h
  /usr/local/include/sha.h
  /usr/local/include/srp.h
  /usr/local/include/srtp.h
  /usr/local/include/ssl.h
  /usr/local/include/ssl2.h
  /usr/local/include/ssl23.h
  /usr/local/include/ssl3.h
  /usr/local/include/stack.h
  /usr/local/include/symhacks.h
  /usr/local/include/tls1.h
  /usr/local/include/ts.h
  /usr/local/include/txt_db.h
  /usr/local/include/ui.h
  /usr/local/include/ui_compat.h
  /usr/local/include/whrlpool.h
  /usr/local/include/x509.h
  /usr/local/include/x509_vfy.h
  /usr/local/include/x509v3.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libgmp.la
  /usr/local/lib/libgmpxx.la

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libboost_atomic.a
  /usr/local/lib/libboost_chrono.a
  /usr/local/lib/libboost_container.a
  /usr/local/lib/libboost_context.a
  /usr/local/lib/libboost_coroutine.a
  /usr/local/lib/libboost_date_time.a
  /usr/local/lib/libboost_exception.a
  /usr/local/lib/libboost_filesystem.a
  /usr/local/lib/libboost_graph.a
  /usr/local/lib/libboost_iostreams.a
  /usr/local/lib/libboost_locale.a
  /usr/local/lib/libboost_log.a
  /usr/local/lib/libboost_log_setup.a
  /usr/local/lib/libboost_math_c99.a
  /usr/local/lib/libboost_math_c99f.a
  /usr/local/lib/libboost_math_c99l.a
  /usr/local/lib/libboost_math_tr1.a
  /usr/local/lib/libboost_math_tr1f.a
  /usr/local/lib/libboost_math_tr1l.a
  /usr/local/lib/libboost_numpy.a
  /usr/local/lib/libboost_prg_exec_monitor.a
  /usr/local/lib/libboost_program_options.a
  /usr/local/lib/libboost_python.a
  /usr/local/lib/libboost_random.a
  /usr/local/lib/libboost_regex.a
  /usr/local/lib/libboost_serialization.a
  /usr/local/lib/libboost_signals.a
  /usr/local/lib/libboost_stacktrace_addr2line.a
  /usr/local/lib/libboost_stacktrace_basic.a
  /usr/local/lib/libboost_stacktrace_noop.a
  /usr/local/lib/libboost_system.a
  /usr/local/lib/libboost_test_exec_monitor.a
  /usr/local/lib/libboost_thread.a
  /usr/local/lib/libboost_timer.a
  /usr/local/lib/libboost_type_erasure.a
  /usr/local/lib/libboost_unit_test_framework.a
  /usr/local/lib/libboost_wave.a
  /usr/local/lib/libboost_wserialization.a
  /usr/local/lib/libff.a
  /usr/local/lib/libgmp.a
  /usr/local/lib/libgmpxx.a
  /usr/local/lib/libopencv_ts.a
  /usr/local/lib/libsnark.a

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  BCKP.opencv3
  boost
  gmp
  python

Warning: Your XQuartz (2.7.9) is outdated.
Please install XQuartz 2.7.11 (or delete the current version).
XQuartz can be updated using Homebrew-Cask by running
  brew cask reinstall xquartz

Warning: Broken symlinks were found. Remove them with `brew prune`:
  /usr/local/bin/docker-credential-osxkeychain.backup
  /usr/local/bin/easy_install-3.6
  /usr/local/bin/hyperkit.backup
  /usr/local/bin/notary.backup
  /usr/local/bin/pip3.6
  /usr/local/bin/vpnkit.backup
  /usr/local/etc/bash_completion.d/_brew_services
  /usr/local/lib/python2.7/site-packages/PIL/PIL/BdfFontFile.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/BmpImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/BufrStubImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/ContainerIO.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/CurImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/DcxImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/DdsImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/EpsImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/ExifTags.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/FitsStubImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/FliImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/FontFile.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/FpxImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/FtexImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/GbrImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/GdImageFile.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/GifImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/GimpGradientFile.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/GimpPaletteFile.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/GribStubImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/Hdf5StubImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/IcnsImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/IcoImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/ImImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/Image.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/ImageChops.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/ImageCms.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/ImageColor.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/ImageDraw.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/ImageDraw2.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/ImageEnhance.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/ImageFile.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/ImageFilter.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/ImageFont.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/ImageGrab.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/ImageMath.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/ImageMode.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/ImageMorph.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/ImageOps.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/ImagePalette.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/ImagePath.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/ImageQt.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/ImageSequence.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/ImageShow.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/ImageStat.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/ImageTk.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/ImageTransform.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/ImageWin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/ImtImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/IptcImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/Jpeg2KImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/JpegImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/JpegPresets.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/McIdasImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/MicImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/MpegImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/MpoImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/MspImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/OleFileIO-README.md
  /usr/local/lib/python2.7/site-packages/PIL/PIL/OleFileIO.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/PSDraw.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/PaletteFile.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/PalmImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/PcdImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/PcfFontFile.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/PcxImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/PdfImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/PixarImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/PngImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/PpmImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/PsdImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/PyAccess.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/SgiImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/SpiderImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/SunImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/TarIO.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/TgaImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/TiffImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/TiffTags.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/WalImageFile.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/WebPImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/WmfImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/XVThumbImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/XbmImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/XpmImagePlugin.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/__init__.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/_binary.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/_imaging.so
  /usr/local/lib/python2.7/site-packages/PIL/PIL/_imagingcms.so
  /usr/local/lib/python2.7/site-packages/PIL/PIL/_imagingft.so
  /usr/local/lib/python2.7/site-packages/PIL/PIL/_imagingmath.so
  /usr/local/lib/python2.7/site-packages/PIL/PIL/_imagingmorph.so
  /usr/local/lib/python2.7/site-packages/PIL/PIL/_imagingtk.so
  /usr/local/lib/python2.7/site-packages/PIL/PIL/_tkinter_finder.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/_util.py
  /usr/local/lib/python2.7/site-packages/PIL/PIL/_webp.so
  /usr/local/lib/python2.7/site-packages/PIL/PIL/features.py
  /usr/local/opt/OpenCV3_brew

