---
eth:
  lotto:
    deployment:
      localAccess:
        rootPath: myLotto/events/game138
      vaultAccess:
        apiVersion: v1
        endpoint: http://127.0.0.1:8200
        token: '1234'
        rootPath: myLotto/events/game138
      dataSetPaths:
        randomOrgApi: config/access/random.org
        proveSeedNonce: setup/nonce/proof
        prizeTierNonce: minting/prizes/tierNonce
        prizeSerialNonce: minting/prizes/serial
        prizeShuffle: minting/prizes/shuffle
        placementKeyPairs: minting/prizes/keyPair
        ticketRandomWitness: event/reveals/random
        ticketPrivateKeys: minting/tickets/privateKeys
        ticketPublicKeys: minting/tickets/publicKeys
        ticketShuffle: minting/tickets/shuffle
        ticketArtwork: minting/tickets/artwork
        ticketTreeSlots: minting/tickets/treeSlots
      keySource:
        mnemonic: number ticket outer asthma wine define arctic butter tower settle answer weird
        key: xprvA3YzySLTBTCvfPiLeA4PuT3XETYhiL7Rkb3XT7z7JZAabgJXfArVWTUYhB4Tccbj43W9f9m7iXs6HZBfcWa4voeQ3wrvUQ3YtNVvFcvXRd3
        path: m/44'/60'/9'/138/2'
      keypairStore:
    prizeMintingPolicy:
      entropySource:
        algorithm: nodeCrypto
        nodeCrypto:
      secureStore: localFiles
      blockLayout:
        gameId:
          fieldSize: 32
          fieldOffset: 0
        serial:
          fieldSize: 160
          fieldOffset: 64
        checkBits:
          fieldSize: 4
          fieldOffset: 32
        prizeTier:
          fieldSize: 10
          fieldOffset: 36
        tierNonce:
          fieldSize: 18
          fieldOffset: 46
        proofNonce:
          fieldSize: 32
          fieldOffset: 224
        privateKey:
          fieldSize: 256
          fieldOffset: 256
      shufflePolicy:
        passCount: 3
        concurrentRuns: 3
        wordBits: 64
        entropySeedBits: 8192
        algorithmKey: hmacDrbg
      tierNoncePolicy:
        batchEntropyBits: 8192
        batchedSetSize: 1536
      serialNoncePolicy:
        entropyBits: 8192
        reseedEvery: 1024
      proofSeed:
        batchBits: 3
        generatedBits: 29
        entryCount: 380001
        batchIds: 5
      entropyDefaults:
        devFake:
          hexSeedBits: abcdef0123456789
        hmacDrbg:
          entropyBitCount: 64
          nonceBitCount: 32
          additionalEntropyWordCount: 2
          additionalEntropyWordBits: 16
        isaac:
          seedBits: 8192
        nodeCrypto:
        randomOrg:
    ticketMintingPolicy:
      entropy:
        algorithm: devFake
        devFake:
          hexSeedBits: 987654321abcdef0
      keyPairStore: localFiles
      keyUuidDirectoryBits: [9, 9, 7, 7]
      curve: ed25519
    eventSpec:
      sponsorId: 9
      gameId: 138
      prizePool:
        secondChanceCount: 1413127
        prizeTiers:
        - tierId: 11
          prizeValue: 75000
          prizeUnits: 0
          instanceCount: 2
          batched: false
        - tierId: 10
          prizeValue: 5000
          prizeUnits: 0
          instanceCount: 16
          batched: false
        - tierId: 9
          prizeValue: 500
          prizeUnits: 0
          instanceCount: 480
          batched: true
        - tierId: 8
          prizeValue: 250
          prizeUnits: 0
          instanceCount: 790
          batched: true
        - tierId: 7
          prizeValue: 100
          prizeUnits: 0
          instanceCount: 4560
          batched: true
        - tierId: 6
          prizeValue: 50
          prizeUnits: 0
          instanceCount: 10735
          batched: true
        - tierId: 5
          prizeValue: 30
          prizeUnits: 0
          instanceCount: 14250
          batched: true
        - tierId: 4
          prizeValue: 20
          prizeUnits: 0
          instanceCount: 47500
          batched: true
        - tierId: 3
          prizeValue: 15
          prizeUnits: 0
          instanceCount: 95045
          batched: true
        - tierId: 2
          prizeValue: 10
          prizeUnits: 0
          instanceCount: 123500
          batched: true
        - tierId: 1
          prizeValue: 5
          prizeUnits: 0
          instanceCount: 190000
          batched: true
    playAssets:
      ticketStyle: randomArt
      randomArt:
        renderingPolicies:
          - name: firstDefault
            imageFieldPolicy: smallSquare
            modelSeedPolicy: 8from7_xy_midRvrs
        imageFieldPolicies:
          - name: smallSquare
            fullSize:
              pixelWidth: 480
              pixelHeight: 480
            thumbnail:
              pixelWidth: 80
              pixelHeight: 80
            unitScale: 1.0
            fitOrFill: square
        modelSeedPolicies:
          - name: 8from7_xy_midFwd
            bitMode: get8From7
            prefixSelect: USE_X
            xRunsForward: true
            yRunsForward: true
            xFromBit: 32
            xToBit: 224
            yFromBit: 32
            yToBit: 224
            useNewModel: false
          - name: 8from7_yx_midRvrs
            bitMode: get8From7
            prefixSelect: USE_Y
            xRunsForward: false
            yRunsForward: false
            xFromBit: 64
            xToBit: 192
            yFromBit: 64
            yToBit: 192
            useNewModel: true
          - name: 64toA_yRx_128bit
            bitMode: base64ToAscii
            prefixSelect: USE_Y
            xRunsForward: false
            yRunsForward: true
            xFromBit: 16
            xToBit: 143
            yFromBit: 53
            yToBit: 188
            useNewModel: true
          - name: mod160_xRy_72bit
            bitMode: mod160
            prefixSelect: USE_X
            xRunsForward: true
            yRunsForward: false
            xFromBit: 11
            xToBit: 84
            yFromBit: 129
            yToBit: 201
            useNewModel: false
          - name: raw_24bit_xy
            bitMode: raw
            prefixSelect: USE_X
            xRunsForward: true
            yRunsForward: true
            xFromBit: 90
            xToBit: 123
            yFromBit: 2
            yToBit: 36
            useNewModel: true
          - name: raw_208bit_Ryx
            bitMode: raw
            prefixSelect: USE_Y
            xRunsForward: false
            yRunsForward: false
            xFromBit: 27
            xToBit: 235
            yFromBit: 23
            yToBit: 231
            useNewModel: false
