---
eth:
  lotto:
    deployment:
      localAccess:
        rootPath: lotto/events/game138
      vaultAccess:
        apiVersion: v1
        endpoint: http://127.0.0.1:8200
        token: '1234'
        rootPath: lotto/events/game138
      vaultPaths:
        proveSeedNonce: setup/nonce/proof
        prizeTierNonce: setup/nonce/tier
        prizeSerialNonce: setup/nonce/serial
        shufflePrizes: setup/shuffle/prizes
        shuffleTickets: setup/shuffle/tickets
        placePrizeWitness: setup/witness/prizes
        ticketRandomWitness: resolve/witness/ticket
        randomOrgApi: setup/access/random.org
      keySource:
        mnemonic: number ticket outer asthma wine define arctic butter tower settle answer
          weird
        key: xprvA3YzySLTBTCvfPiLeA4PuT3XETYhiL7Rkb3XT7z7JZAabgJXfArVWTUYhB4Tccbj43W9f9m7iXs6HZBfcWa4voeQ3wrvUQ3YtNVvFcvXRd3
        path: m/44'/60'/9'/138/2'
    setupPolicy:
      randomSource: nodeCrypto
      secureStore: localFiles
      blockLayout:
        gameId:
          fieldSize: 32
          fieldOffset: 0
        serial:
          fieldSize: 160
          fieldOffset: 64
        checkBits:
          fieldSize: 4
          fieldOffset: 32
        prizeTier:
          fieldSize: 10
          fieldOffset: 36
        tierNonce:
          fieldSize: 18
          fieldOffset: 46
        proofNonce:
          fieldSize: 32
          fieldOffset: 224
      shufflePolicy:
        sweepCount: 3
        sequenceWidth: 4
        wordBits: 64
        entropyBits: 8192
        reseedEvery: 256
      tierNoncePolicy:
        entropyBits: 8192
        reseedEvery: 1536
      serialNoncePolicy:
        entropyBits: 8192
        reseedEvery: 1024
      proofSeed:
        batchBits: 3
        generatedBits: 29
        entryCount: 380001
        batchIds: 5
    eventSpec:
      sponsorId: 9
      gameId: 138
      prizePool:
        secondChanceCount: 1413127
        prizeTiers:
        - tierId: 11
          prizeValue: 75000
          prizeUnits: 0
          instanceCount: 2
          batched: false
        - tierId: 10
          prizeValue: 5000
          prizeUnits: 0
          instanceCount: 16
          batched: false
        - tierId: 9
          prizeValue: 500
          prizeUnits: 0
          instanceCount: 480
          batched: true
        - tierId: 8
          prizeValue: 250
          prizeUnits: 0
          instanceCount: 790
          batched: true
        - tierId: 7
          prizeValue: 100
          prizeUnits: 0
          instanceCount: 4560
          batched: true
        - tierId: 6
          prizeValue: 50
          prizeUnits: 0
          instanceCount: 10735
          batched: true
        - tierId: 5
          prizeValue: 30
          prizeUnits: 0
          instanceCount: 14250
          batched: true
        - tierId: 4
          prizeValue: 20
          prizeUnits: 0
          instanceCount: 47500
          batched: true
        - tierId: 3
          prizeValue: 15
          prizeUnits: 0
          instanceCount: 95045
          batched: true
        - tierId: 2
          prizeValue: 10
          prizeUnits: 0
          instanceCount: 123500
          batched: true
        - tierId: 1
          prizeValue: 5
          prizeUnits: 0
          instanceCount: 190000
          batched: true

